import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowUpRight,Bell,Box,CheckCircle2,ChevronRight,Clock3,MapPin,PackageCheck,Search,Sparkles,Truck,XCircle,UserRound,ShieldAlert,BrainCircuit,Play,ThumbsDown,ThumbsUp,History,RefreshCw,Radio,Zap} from 'lucide-react';
import './App.css';
import './Goal6.css';

const API=import.meta.env.VITE_API_URL || '/api';
const nav=['Overview','Shipments','Exceptions','Operations','Analytics','Customer','Notifications'];

function Badge({children}){return <span className={`badge ${String(children).toLowerCase().replaceAll(' ','-')}`}>{children}</span>}
function StatCard({label,value,meta,icon:Icon,tone}){return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19}/></div><div><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-meta">{meta}</div></div></div>}

export default function App(){
 const[token,setToken]=useState(localStorage.getItem('routeiq_token')||''),[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('routeiq_user')||'null')}catch{return null}}),[notifications,setNotifications]=useState([]),[users,setUsers]=useState([]),[dashboard,setDashboard]=useState(null),[shipments,setShipments]=useState([]),[exceptions,setExceptions]=useState([]),[operators,setOperators]=useState([]),[ai,setAi]=useState({status:'Offline',pendingInsights:0,monitoredShipments:0}),[insights,setInsights]=useState([]),[activity,setActivity]=useState([]),[audit,setAudit]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[active,setActive]=useState('Overview'),[working,setWorking]=useState(null),[aiRefreshing,setAiRefreshing]=useState(false),[analytics,setAnalytics]=useState(null),[trackingId,setTrackingId]=useState('SHP-IND-10401'),[tracking,setTracking]=useState(null),[trackingLoading,setTrackingLoading]=useState(false),[trackingError,setTrackingError]=useState('');

 const load=async({refreshAI=false}={})=>{
  try{
   const [d,s,e,o,a,i,ac,au,an,n,u]=await Promise.all([
    fetch(`${API}/dashboard`).then(r=>r.json()),fetch(`${API}/shipments`).then(r=>r.json()),fetch(`${API}/exceptions`).then(r=>r.json()),fetch(`${API}/operators`).then(r=>r.json()),
    fetch(`${API}/ai/status`).then(r=>r.json()),fetch(`${API}/ai/insights${refreshAI?'?refresh=true':''}`).then(r=>r.json()),
    fetch(`${API}/operations/activity?limit=12`).then(r=>r.json()),fetch(`${API}/audit?limit=12`).then(r=>r.json()),fetch(`${API}/analytics`).then(r=>r.json()),fetch(`${API}/notifications`).then(r=>r.json()),user?.role==='admin'?fetch(`${API}/users`).then(r=>r.json()):Promise.resolve({data:[]})
   ]);
   setDashboard(d.data);setShipments(s.data);setExceptions(e.data);setOperators(o.data);setAi(a.data);setInsights(i.data||[]);setActivity(ac.data||[]);setAudit(au.data||[]);setAnalytics(an.data);setNotifications(n.data||[]);setUsers(u.data||[]);
   if(!selected&&s.data[0])setSelected(s.data[0]); else if(selected){const fresh=s.data.find(x=>x.id===selected.id);if(fresh)setSelected(fresh);}
  }catch{setNotice('Unable to connect to logistics API');}finally{setLoading(false);}
 };
 useEffect(()=>{load();const timer=setInterval(()=>load(),8000);return()=>clearInterval(timer)},[]);
 const filtered=useMemo(()=>shipments.filter(s=>(filter==='All'||s.status===filter)&&(!query||[s.id,s.origin,s.destination,s.currentLocation].join(' ').toLowerCase().includes(query.toLowerCase()))),[shipments,query,filter]);

 const login=async(username,password)=>{try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Login failed');localStorage.setItem('routeiq_token',d.data.token);localStorage.setItem('routeiq_user',JSON.stringify(d.data.user));setToken(d.data.token);setUser(d.data.user);setLoading(true);setNotice('Login successful');setTimeout(()=>setNotice(''),2500);}catch(e){setNotice(e.message)}};
 const logout=async()=>{try{await fetch(`${API}/auth/logout`,{method:'POST',headers:{Authorization:`Bearer ${token}`}})}catch{} localStorage.removeItem('routeiq_token');localStorage.removeItem('routeiq_user');setToken('');setUser(null);setActive('Overview');};
 const authHeaders=()=>token?{Authorization:`Bearer ${token}`}:{};
 const act=async(path,body,msg)=>{
  setWorking(path);
  try{const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(body||{})});const data=await r.json();if(!r.ok)throw new Error(data.error||msg);setNotice(data.message||msg);await load();setTimeout(()=>setNotice(''),3000)}
  catch(err){setNotice(err.message||'Action failed');setTimeout(()=>setNotice(''),3500)}
  finally{setWorking(null)}
 };
 const simulate=type=>act(`/simulation/${type}`,{shipmentId:selected?.id},'Updated');
 const resolve=async e=>act(`/exceptions/${e.id}/resolve`,{},'Exception resolved successfully');
 const assign=async e=>act(`/exceptions/${e.id}/assign`,{operatorId:operators[0]?.id},`Assigned to ${operators[0]?.name}`);
 const investigate=async e=>act(`/exceptions/${e.id}/investigate`,{},'Investigation started');

 const analyzeAI=async()=>{setAiRefreshing(true);try{const r=await fetch(`${API}/ai/analyze`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI analysis failed');setNotice(d.message);await load();setTimeout(()=>setNotice(''),3000)}catch(e){setNotice(e.message)}finally{setAiRefreshing(false)}};
 const aiAction=async(id,action)=>act(`/ai/insights/${id}/${action}`,{approvedBy:'Abhishek',rejectedBy:'Abhishek',executedBy:'Abhishek'},action==='approve'?'AI recommendation approved':action==='reject'?'AI recommendation rejected':'AI action executed');
 const searchTracking=async()=>{setTrackingLoading(true);setTrackingError('');try{const r=await fetch(`${API}/tracking/${encodeURIComponent(trackingId.trim())}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'Tracking ID not found');setTracking(data.data)}catch(e){setTracking(null);setTrackingError(e.message)}finally{setTrackingLoading(false)}};

 if(!token)return <LoginScreen onLogin={login} notice={notice}/>;
 if(loading)return <div className="loading"><div className="spinner"/><span>Loading operations center…</span></div>;

 return <div className="app-shell">
  <aside className="sidebar">
   <div className="brand"><div className="brand-mark"><Truck size={20}/></div><div><strong>RouteIQ</strong><span>Logistics OS</span></div></div>
   <div className="workspace"><span>WORKSPACE</span><button className="workspace-btn"><span className="avatar">OP</span><span>Operations Team</span><ChevronRight size={15}/></button></div>
   <nav>{nav.map((item,i)=>{const I=[Activity,Box,AlertTriangle,CheckCircle2,ArrowUpRight,Search,Bell][i];return <button key={item} className={active===item?'active':''} onClick={()=>setActive(item)}><I size={18}/>{item}{item==='Exceptions'&&<em>{exceptions.length}</em>}{item==='Operations'&&ai.pendingInsights>0&&<em className="ai-count">{ai.pendingInsights}</em>}</button>})}</nav>
   <div className="sidebar-bottom"><div className="ai-mini"><Sparkles size={17}/><div><b>AI Agent</b><span>{ai.status==='Monitoring'?'Monitoring system':'Offline'}</span></div><i className={ai.status==='Monitoring'?'':'off'}/></div><div className="user-row"><span className="avatar">A</span><div><b>Abhishek</b><span>Administrator</span></div><Bell size={17}/></div></div>
  </aside>

  <main className="main">
   <header className="topbar">
    <div><div className="eyebrow">OPERATIONS / {active.toUpperCase()}</div><h1>{active==='Exceptions'?'Exception Command Center':active==='Operations'?'AI Operations Center':active==='Notifications'?'Customer Communication Center':'Logistics Control Center'}</h1><p>{active==='Exceptions'?'Investigate, assign and resolve shipment problems.':active==='Operations'?'AI monitors operations, recommends actions, and records every decision.':active==='Notifications'?'AI drafts customer messages; humans approve before sending.':'Detect exceptions, understand impact, and take action.'}</p></div>
    <div className="top-actions"><div className="live"><span/> {ai.status==='Monitoring'?'AI monitoring live':'System monitoring'}</div><div className="role-chip"><UserRound size={13}/>{user?.name||'User'} · {user?.role}</div><button className="icon-btn" onClick={logout} title="Logout"><Bell size={18}/></button>{user?.role!=='viewer'&&<button className="demo-btn" onClick={()=>simulate('delay')}><Activity size={16}/> Simulate delay</button>}</div>
   </header>
   {notice&&<div className="toast"><CheckCircle2 size={17}/>{notice}</div>}

   {active==='Exceptions'?<ExceptionView exceptions={exceptions} operators={operators} working={working} assign={assign} investigate={investigate} resolve={resolve}/>:active==='Operations'?<AIOperations insights={insights} ai={ai} activity={activity} audit={audit} working={working} refreshing={aiRefreshing} analyze={analyzeAI} action={aiAction}/>:active==='Analytics'?<AnalyticsView dashboard={dashboard} analytics={analytics}/>:active==='Customer'?<CustomerView trackingId={trackingId} setTrackingId={setTrackingId} tracking={tracking} trackingLoading={trackingLoading} trackingError={trackingError} searchTracking={searchTracking}/>:active==='Notifications'?<NotificationCenter notifications={notifications} shipments={shipments} selected={selected} working={working} act={act}/>:<>
    <section className="stats"><StatCard label="Total shipments" value={dashboard.total} meta="Across all active routes" icon={Box} tone="blue"/><StatCard label="Delivered" value={dashboard.delivered} meta="Completed successfully" icon={PackageCheck} tone="green"/><StatCard label="Delayed" value={dashboard.delayed} meta="Needs attention" icon={Clock3} tone="red"/><StatCard label="At risk" value={dashboard.atRisk} meta="SLA may be impacted" icon={AlertTriangle} tone="amber"/><div className="sla-card"><div className="sla-head"><span>SLA PERFORMANCE</span><b>{dashboard.sla}%</b></div><div className="progress"><span style={{width:`${dashboard.sla}%`}}/></div><small>Target ≥ 95%</small></div></section>
    <section className="grid-top"><div className="panel exceptions"><div className="panel-head"><div><h2>Priority exceptions</h2><p>Shipments that need an operator decision</p></div><button className="text-btn" onClick={()=>setActive('Exceptions')}>View all <ChevronRight size={15}/></button></div>{shipments.filter(s=>s.status==='Delayed'||s.status==='At Risk').slice(0,4).map(s=><button className={`exception-row ${selected?.id===s.id?'selected':''}`} key={s.id} onClick={()=>setSelected(s)}><span className="severity">{s.status==='Delayed'?<XCircle size={17}/>:<AlertTriangle size={17}/>}</span><span className="exception-main"><b>{s.id}</b><span>{s.origin} → {s.destination}</span></span><span className="exception-reason">{s.reason}</span><Badge>{s.status}</Badge><ChevronRight size={17}/></button>)}</div>
     <div className="panel ai-panel"><div className="ai-title"><div className="ai-icon"><Sparkles size={18}/></div><div><h2>AI operations insight</h2><p>{ai.status} · {ai.monitoredShipments} shipments monitored</p></div><span className="pulse"/></div><div className="insight"><div className="insight-label">AI RECOMMENDATION</div><h3>{insights[0]?.title||'No new AI insights'}</h3><p>{insights[0]?.explanation||'The AI agent is monitoring your network for operational patterns.'}</p><button onClick={()=>setActive('Operations')}>Open AI Operations Center <ArrowUpRight size={15}/></button></div><div className="ai-foot"><span><Sparkles size={14}/> {ai.pendingInsights} recommendations ready</span><span>Auto-refresh 8s</span></div></div>
    </section>
    <ShipmentTable filtered={filtered} selected={selected} setSelected={setSelected} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter}/>
    <section className="bottom-grid"><div className="panel selected-card"><div className="panel-head"><div><h2>Selected shipment</h2><p>Live tracking detail</p></div>{selected&&<Badge>{selected.status}</Badge>}</div>{selected&&<div className="selected-content"><div className="shipment-hero"><div className="big-icon"><Truck size={25}/></div><div><b>{selected.id}</b><span>{selected.carrier}</span></div><div className="eta"><small>ETA</small><b>{new Date(selected.eta).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</b></div></div><div className="route-strip"><div><small>ORIGIN</small><b>{selected.origin}</b></div><div className="line"><span/><span/><span/></div><div><small>DESTINATION</small><b>{selected.destination}</b></div></div><div className="current-location"><MapPin size={16}/><span>Currently at <b>{selected.currentLocation}</b></span><button onClick={()=>simulate('deliver')}>Simulate delivery</button></div></div>}</div><div className="panel quick-actions"><div className="panel-head"><div><h2>Quick actions</h2><p>Operator tools for the live demo</p></div></div><button onClick={()=>simulate('delay')}><AlertTriangle size={18}/><span><b>Simulate shipment delay</b><small>Create a live exception</small></span><ChevronRight size={16}/></button><button onClick={()=>simulate('deliver')}><CheckCircle2 size={18}/><span><b>Mark shipment delivered</b><small>Update status instantly</small></span><ChevronRight size={16}/></button></div></section>
   </>}
  </main>
 </div>;
}


function LoginScreen({onLogin,notice}){
 const[u,setU]=useState('admin'),[p,setP]=useState('Admin@123'),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);await onLogin(u,p);setBusy(false)};
 return <div className="login-page"><div className="login-card"><div className="brand login-brand"><div className="brand-mark"><Truck size={20}/></div><div><strong>RouteIQ</strong><span>Logistics OS</span></div></div><div className="login-kicker">SECURE OPERATIONS ACCESS</div><h1>Sign in to RouteIQ</h1><p>Access shipment operations, AI decisions and customer communications.</p><form onSubmit={submit}><label>Username<input value={u} onChange={e=>setU(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={p} onChange={e=>setP(e.target.value)} autoComplete="current-password"/></label>{notice&&<div className="login-error">{notice}</div>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><div className="demo-accounts"><b>Local demo accounts</b><span>admin / Admin@123</span><span>operator / Operator@123</span><span>viewer / Viewer@123</span></div></div></div>
}

function NotificationCenter({notifications,shipments,selected,working,act}){
 const[draft,setDraft]=useState(selected?.id||shipments.find(s=>s.status==='Delayed'||s.status==='At Risk')?.id||'');
 useEffect(()=>{if(selected?.id)setDraft(selected.id)},[selected?.id]);
 const candidates=shipments.filter(s=>s.status==='Delayed'||s.status==='At Risk');
 return <section className="notification-page"><div className="notification-hero panel"><div><div className="customer-kicker"><Sparkles size={14}/> AI CUSTOMER COMMUNICATION</div><h2>Notify customers before they ask.</h2><p>AI drafts an operationally accurate message. An authorized human must approve it before a demo notification is sent.</p></div><div className="approval-flow"><span>AI Draft</span><ChevronRight size={14}/><span>Human Approval</span><ChevronRight size={14}/><span>Send</span></div></div><div className="notification-compose panel"><div className="panel-head"><div><h2>Create customer notification</h2><p>Select a delayed or at-risk shipment and generate a customer-safe message.</p></div><Badge>Human approval required</Badge></div><div className="notification-compose-row"><select value={draft} onChange={e=>setDraft(e.target.value)}><option value="">Select shipment</option>{candidates.map(s=><option key={s.id} value={s.id}>{s.id} · {s.status} · {s.origin} → {s.destination}</option>)}</select><button disabled={!draft||working==='/notifications/generate'} onClick={()=>act('/notifications/generate',{shipmentId:draft},'AI customer message generated')}>{working==='/notifications/generate'?'Generating…':'Generate AI message'}</button></div></div><div className="notification-list">{notifications.map(n=><article className="notification-card panel" key={n.id}><div className="notification-card-head"><div><Badge>{n.status}</Badge><h3>{n.subject}</h3><span>{n.shipmentId} · {n.channel} · {n.customerName}</span></div><small>{new Date(n.createdAt).toLocaleString()}</small></div><p>{n.message}</p><div className="notification-actions">{n.status==='Pending Approval'&&<><button className="secondary" onClick={()=>act('/notifications/'+n.id+'/reject',{},'Customer message rejected')}>Reject</button><button className="primary" onClick={()=>act('/notifications/'+n.id+'/approve',{},'Customer message approved')}>Approve</button></>}{n.status==='Approved'&&<button className="primary" onClick={()=>act('/notifications/'+n.id+'/send',{},'Notification sent (demo)')}>Send notification</button>}{n.status==='Sent'&&<span className="sent-label"><CheckCircle2 size={14}/> Sent in demo mode</span>}</div></article>)}{!notifications.length&&<div className="empty"><Bell size={30}/><b>No customer notifications yet</b><span>Generate one from a delayed shipment to start the approval workflow.</span></div>}</div></section>
}

function ShipmentTable({filtered,selected,setSelected,query,setQuery,filter,setFilter}){return <section className="panel shipment-table"><div className="panel-head table-head"><div><h2>Shipment activity</h2><p>Real-time operational view of your network</p></div><div className="table-tools"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search shipment, city…"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{['Delivered','In Transit','Delayed','At Risk'].map(s=><option key={s}>{s}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>Shipment</th><th>Route</th><th>Current location</th><th>Status</th><th>ETA</th><th>SLA</th></tr></thead><tbody>{filtered.slice(0,10).map(s=><tr key={s.id} className={selected?.id===s.id?'row-selected':''} onClick={()=>setSelected(s)}><td><b>{s.id}</b><span>{s.carrier}</span></td><td><span className="route"><MapPin size={14}/>{s.origin} <ChevronRight size={12}/> {s.destination}</span></td><td>{s.currentLocation}</td><td><Badge>{s.status}</Badge></td><td>{new Date(s.eta).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td><span className={`sla-dot ${s.sla.toLowerCase().replaceAll(' ','-')}`}/>{s.sla}</td></tr>)}</tbody></table></div></section>}

function AIOperations({insights,ai,activity,audit,working,refreshing,analyze,action}){
 return <section className="ai-center">
  <div className="ai-commandbar panel"><div className="ai-agent-status"><div className="ai-big-icon"><BrainCircuit size={25}/></div><div><span>ROUTEIQ OPERATIONS AGENT</span><h2>{ai.status}</h2><p>Monitoring {ai.monitoredShipments} shipments · {ai.activeExceptions} active exceptions</p></div></div><div className="ai-command-actions"><button className="secondary-ai" onClick={analyze} disabled={refreshing}><RefreshCw size={15} className={refreshing?'spin':''}/>{refreshing?'Analyzing…':'Run AI analysis'}</button><div className="monitor-pill"><Radio size={14}/> Auto-refresh active</div></div></div>
  <div className="ai-metrics"><div className="panel ai-metric"><span>Pending insights</span><b>{ai.pendingInsights}</b><small>Awaiting operator decision</small></div><div className="panel ai-metric"><span>Monitored shipments</span><b>{ai.monitoredShipments}</b><small>Live network coverage</small></div><div className="panel ai-metric"><span>Active exceptions</span><b>{ai.activeExceptions}</b><small>Operational workload</small></div><div className="panel ai-metric"><span>Agent mode</span><b>Live</b><small>Analysis engine running</small></div></div>
  <div className="ai-main-grid">
   <div className="panel ai-insights-panel"><div className="panel-head"><div><h2>AI recommendations</h2><p>Review before the agent takes an operational action</p></div><span className="count-badge">{insights.length}</span></div>
    <div className="insight-list">{insights.map(x=><article className="ai-insight-card" key={x.id}><div className="ai-insight-head"><div className={`severity-icon ${x.severity.toLowerCase()}`}>{x.severity==='High'?<AlertTriangle size={17}/>:<Sparkles size={17}/>}</div><div className="ai-insight-title"><div><Badge>{x.severity}</Badge><span>{x.type.replaceAll('_',' ')}</span></div><h3>{x.title}</h3></div><span className={`ai-status ${x.status.toLowerCase()}`}>{x.status}</span></div><p className="ai-explanation">{x.explanation}</p><div className="ai-recommendation"><Zap size={15}/><div><small>RECOMMENDED ACTION</small><b>{x.recommendation}</b></div></div><div className="ai-confidence"><span>AI confidence</span><b>{Math.round(x.confidence*100)}%</b><div><span style={{width:`${x.confidence*100}%`}}/></div></div>{x.status==='Pending'&&<div className="ai-actions"><button className="reject" onClick={()=>action(x.id,'reject')} disabled={working===`/ai/insights/${x.id}/reject`}><ThumbsDown size={14}/> Reject</button><button className="approve" onClick={()=>action(x.id,'approve')} disabled={working===`/ai/insights/${x.id}/approve`}><ThumbsUp size={14}/> Approve</button></div>}{x.status==='Approved'&&<div className="ai-actions"><button className="execute" onClick={()=>action(x.id,'execute')} disabled={working===`/ai/insights/${x.id}/execute`}><Play size={14}/> Execute approved action</button></div>}</article>)}{!insights.length&&<div className="empty"><CheckCircle2 size={30}/><b>No pending AI recommendations</b><span>Run an analysis when you want a fresh scan.</span></div>}</div>
   </div>
   <div className="ai-side"><div className="panel activity-panel"><div className="panel-head"><div><h2>Live activity</h2><p>System and AI events</p></div><Activity size={16}/></div><div className="activity-feed">{activity.slice(0,8).map(x=><div className="activity-item" key={x.id}><span className="activity-dot"/><div><b>{x.message}</b><small>{x.type} · {new Date(x.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div></div>)}</div></div>
   <div className="panel audit-panel"><div className="panel-head"><div><h2>Audit trail</h2><p>Human approvals and AI actions</p></div><History size={16}/></div><div className="audit-feed">{audit.slice(0,7).map(x=><div className="audit-item" key={x.id}><div><b>{x.action}</b><span>{x.actor}</span></div><small>{new Date(x.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>)}</div></div></div>
  </div>
 </section>
}

function LegacyAnalyticsView({dashboard,shipments}){const rows=['Delivered','In Transit','Delayed','At Risk'].map(status=>({status,count:shipments.filter(s=>s.status===status).length}));return <section className="analytics-grid"><div className="panel analytics-hero"><div><span>NETWORK PERFORMANCE</span><h2>{dashboard.sla}% SLA performance</h2><p>Live operational snapshot across {dashboard.total} shipments.</p></div><div className="analytics-bar"><span style={{width:`${dashboard.sla}%`}}/></div></div>{rows.map(r=><div className="panel analytics-stat" key={r.status}><span>{r.status}</span><b>{r.count}</b><small>shipments</small></div>)}</section>}

function AnalyticsView({dashboard,analytics}){if(!analytics)return <div className='loading'><div className='spinner'/><span>Loading analytics…</span></div>;const max=Math.max(...analytics.delayReasons.map(x=>x.count),1);return <section className='analytics-page'><div className='analytics-hero panel'><div><span>NETWORK PERFORMANCE</span><h2>{analytics.sla}% SLA performance</h2><p>Live operational snapshot across {analytics.total} shipments.</p></div><div className='analytics-bar'><span style={{width:analytics.sla+'%'}}/></div></div><div className='analytics-kpis'>{Object.entries(analytics.statuses).map(([k,v])=><div className='panel analytics-stat' key={k}><span>{k}</span><b>{v}</b><small>shipments</small></div>)}</div><div className='analytics-columns'><div className='panel analytics-list'><div className='panel-head'><div><h2>Carrier performance</h2><p>Delivery and issue rates by carrier</p></div></div>{analytics.carrierPerformance.map(c=><div className='metric-row' key={c.carrier}><div><b>{c.carrier}</b><span>{c.total} shipments · {c.delayed+c.atRisk} active issues</span></div><strong>{c.deliveryRate}%</strong><div className='mini-bar'><span style={{width:c.deliveryRate+'%'}}/></div></div>)}</div><div className='panel analytics-list'><div className='panel-head'><div><h2>Delay reasons</h2><p>Current customer-impacting issues</p></div></div>{analytics.delayReasons.map(x=><div className='reason-row' key={x.reason}><div><b>{x.reason}</b><span>{x.count} shipments</span></div><div className='reason-track'><span style={{width:Math.round(x.count/max*100)+'%'}}/></div></div>)}</div></div><div className='panel analytics-list'><div className='panel-head'><div><h2>Route risk</h2><p>Routes with the most active delivery issues</p></div></div><div className='route-grid'>{analytics.routePerformance.map(r=><div className='route-risk' key={r.route}><b>{r.route}</b><span>{r.total} total · {r.delayed} delayed · {r.atRisk} at risk</span></div>)}</div></div></section>}

function CustomerView({trackingId,setTrackingId,tracking,trackingLoading,trackingError,searchTracking}){return <section className='customer-page'><div className='customer-hero'><div className='customer-kicker'><PackageCheck size={16}/> CUSTOMER TRACKING</div><h2>Track your shipment</h2><p>Enter your tracking ID to see live location, ETA, status and delivery timeline.</p><div className='tracking-search'><Search size={18}/><input value={trackingId} onChange={e=>setTrackingId(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchTracking()} placeholder='e.g. SHP-IND-10401'/><button onClick={searchTracking} disabled={trackingLoading}>{trackingLoading?'Tracking…':'Track shipment'}</button></div>{trackingError&&<div className='tracking-error'><XCircle size={15}/>{trackingError}</div>}<div className='sample-hint'>Demo tracking IDs: SHP-IND-10401, SHP-IND-10402, SHP-IND-10403</div></div>{tracking&&<div className='customer-result'><div className='panel customer-status'><div className='customer-status-head'><div><span>TRACKING ID</span><h2>{tracking.trackingId}</h2><p>{tracking.origin} → {tracking.destination}</p></div><Badge>{tracking.status}</Badge></div><div className='customer-summary'><div><small>CURRENT LOCATION</small><b><MapPin size={14}/>{tracking.currentLocation}</b></div><div><small>ESTIMATED DELIVERY</small><b>{new Date(tracking.eta).toLocaleString([], {weekday:'short',hour:'2-digit',minute:'2-digit'})}</b></div><div><small>SLA</small><b>{tracking.sla}</b></div><div><small>CARRIER</small><b>{tracking.carrier}</b></div></div><div className='customer-message'><Sparkles size={15}/><span>{tracking.statusMessage}{tracking.status!=='Delivered'&&tracking.reason?' · '+tracking.reason:''}</span></div></div><div className='panel timeline-panel'><div className='panel-head'><div><h2>Shipment timeline</h2><p>Latest operational milestones</p></div><span className='timeline-live'>LIVE</span></div><div className='timeline'>{tracking.timeline.map((t,i)=><div className={'timeline-item '+(t.done?'done':'')} key={t.label}><span className='timeline-dot'>{t.done?<CheckCircle2 size={14}/>:<Clock3 size={13}/>}</span><div><b>{t.label}</b><span>{t.time}</span></div>{i<tracking.timeline.length-1&&<i/>}</div>)}</div></div></div>}</section>}

function ExceptionView({exceptions,operators,working,assign,investigate,resolve}){return <section className="exception-center"><div className="exception-summary"><div><ShieldAlert size={20}/><b>{exceptions.length} active exceptions</b><span>Problems requiring operator attention</span></div><div className="summary-chips"><span><b>{exceptions.filter(e=>e.priority==='High').length}</b> High priority</span><span><b>{exceptions.filter(e=>e.status==='Investigating').length}</b> Investigating</span></div></div><div className="exception-list">{exceptions.map(e=><article className="exception-card" key={e.id}><div className="exception-card-top"><div className={`exception-type ${e.priority.toLowerCase()}`}><AlertTriangle size={18}/></div><div className="exception-card-title"><div><b>{e.id}</b><Badge>{e.type}</Badge><Badge>{e.priority}</Badge></div><h2>{e.shipmentId}</h2><p>{e.reason}</p></div><span className="exception-status">{e.status}</span></div><div className="exception-grid"><div><small>IMPACT</small><b>{e.impact}</b></div><div><small>RECOMMENDED ACTION</small><b>{e.recommendedAction}</b><span>{e.recommendationDetail}</span></div><div><small>ASSIGNEE</small><b>{e.assignee?.name||'Unassigned'}</b></div></div><div className="exception-actions"><button className="secondary" onClick={()=>assign(e)} disabled={working===`/exceptions/${e.id}/assign`}><UserRound size={14}/>{e.assignee?'Reassign':'Assign operator'}</button><button className="secondary" onClick={()=>investigate(e)} disabled={working===`/exceptions/${e.id}/investigate`}><Search size={14}/>{working===`/exceptions/${e.id}/investigate`?'Investigating…':'Investigate'}</button><button className="primary" onClick={()=>resolve(e)} disabled={working===`/exceptions/${e.id}/resolve`}><CheckCircle2 size={14}/>Resolve exception</button></div></article>)}</div>{!exceptions.length&&<div className="empty"><CheckCircle2 size={30}/><b>All exceptions resolved</b><span>The operations queue is clear.</span></div>}</section>}
